theme: jekyll-theme-midnight

# 基本信息
**姓 名**  ：陈春洋         
**民 族**  ：汉        
**出生年月**：1997.02   
**电 话**  ：18723748632     
**邮 箱**：enunang@foxmail.com    
**住 址**：重庆     
**身 高**：180cm    
**毕业院校**  ：重庆工程学院 
